# Generated by Django 3.2.10 on 2021-12-26 16:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('tagid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('interests', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, default='/profilepictures/defaultProfile.png', null=True, upload_to='profilepictures/')),
                ('credits', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offerid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('picture', models.ImageField(default='images/logo.png', upload_to='images/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=20)),
                ('credits', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)])),
                ('numberOfParticipants', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('event', 'Event'), ('gathering', 'Gathering')], max_length=50)),
                ('eventstatus', models.CharField(choices=[('done', 'Done'), ('canceled', 'Cancel'), ('inprogress', 'In Progress')], max_length=50)),
                ('hashtags', models.ManyToManyField(blank=True, to='base.Tags')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=50)),
                ('voteid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('voteTotal', models.IntegerField(blank=True, default=0, null=True)),
                ('voteRatio', models.IntegerField(blank=True, default=0, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offers')),
            ],
        ),
        migrations.CreateModel(
            name='Attendants',
            fields=[
                ('requestid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('approval', 'Approval'), ('approved', 'Approve'), ('rejected', 'Reject')], max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offers')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profiles')),
            ],
            options={
                'unique_together': {('owner', 'event')},
            },
        ),
    ]
