# Generated by Django 3.2.10 on 2022-01-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220102_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendants',
            name='offerstatus',
            field=models.CharField(choices=[('done', 'Done'), ('canceled', 'Cancel'), ('inprogress', 'In Progress')], default='inprogress', max_length=50),
        ),
    ]
