# Generated by Django 3.2.10 on 2022-01-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_attendants_offerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='exchange',
            field=models.CharField(choices=[('done', 'Done'), ('canceled', 'Cancel'), ('inprogress', 'In Progress')], default='no', max_length=50),
        ),
    ]
