# Generated by Django 3.2.10 on 2022-01-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_offers_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendants',
            name='exchange',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='offers',
            name='exchange',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=50),
        ),
    ]
