# Generated by Django 3.2.10 on 2022-01-08 17:52

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220102_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='eventlocation',
            field=location_field.models.plain.PlainLocationField(default='41.083556, 29.050598', max_length=63),
        ),
        migrations.AddField(
            model_name='profiles',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='41.083556, 29.050598', max_length=63),
        ),
        migrations.AlterField(
            model_name='offers',
            name='location',
            field=models.CharField(blank=True, default='map', max_length=20),
        ),
    ]
