# Generated by Django 3.2.10 on 2022-01-08 21:51

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_offers_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='eventlocation',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
