# Generated by Django 3.2.10 on 2022-01-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_offers_eventlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='location',
            field=models.CharField(blank=True, default='london', max_length=1000),
        ),
    ]
